/* automatically generated by rust-bindgen 0.72.1 */

// @generated by tools/generate-flutter-embedder-bindings; do not edit.
// Flutter engine revision: 692136cb6582dbfc5af3fb33c2515a069f2f66d0
// Flutter source revision: 5fc346839b5d0eef006ed8404392afb4dfae428d
// Source embedder.h SHA-256: 1c6b72beb8d1ded1c0c111974210efd1ae4b7c09ac595a0865158ef6f76a54ed

pub const FLUTTER_ENGINE_VERSION: u32 = 1;
pub const FlutterEngineResult_kSuccess: FlutterEngineResult = 0;
pub const FlutterEngineResult_kInvalidLibraryVersion: FlutterEngineResult = 1;
pub const FlutterEngineResult_kInvalidArguments: FlutterEngineResult = 2;
pub const FlutterEngineResult_kInternalInconsistency: FlutterEngineResult = 3;
pub type FlutterEngineResult = ::std::os::raw::c_uint;
pub const FlutterRendererType_kOpenGL: FlutterRendererType = 0;
pub const FlutterRendererType_kSoftware: FlutterRendererType = 1;
pub const FlutterRendererType_kMetal: FlutterRendererType = 2;
pub const FlutterRendererType_kVulkan: FlutterRendererType = 3;
pub type FlutterRendererType = ::std::os::raw::c_uint;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureAccessibleNavigation:
    FlutterAccessibilityFeature = 1;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureInvertColors:
    FlutterAccessibilityFeature = 2;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureDisableAnimations:
    FlutterAccessibilityFeature = 4;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureBoldText:
    FlutterAccessibilityFeature = 8;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureReduceMotion:
    FlutterAccessibilityFeature = 16;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureHighContrast:
    FlutterAccessibilityFeature = 32;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureOnOffSwitchLabels:
    FlutterAccessibilityFeature = 64;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureNoAnnounce:
    FlutterAccessibilityFeature = 128;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureNoAutoPlayAnimatedImages:
    FlutterAccessibilityFeature = 256;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureNoAutoPlayVideos:
    FlutterAccessibilityFeature = 512;
pub const FlutterAccessibilityFeature_kFlutterAccessibilityFeatureDeterministicCursor:
    FlutterAccessibilityFeature = 1024;
pub type FlutterAccessibilityFeature = ::std::os::raw::c_uint;
pub const FlutterSemanticsAction_kFlutterSemanticsActionTap: FlutterSemanticsAction = 1;
pub const FlutterSemanticsAction_kFlutterSemanticsActionLongPress: FlutterSemanticsAction = 2;
pub const FlutterSemanticsAction_kFlutterSemanticsActionScrollLeft: FlutterSemanticsAction = 4;
pub const FlutterSemanticsAction_kFlutterSemanticsActionScrollRight: FlutterSemanticsAction = 8;
pub const FlutterSemanticsAction_kFlutterSemanticsActionScrollUp: FlutterSemanticsAction = 16;
pub const FlutterSemanticsAction_kFlutterSemanticsActionScrollDown: FlutterSemanticsAction = 32;
pub const FlutterSemanticsAction_kFlutterSemanticsActionIncrease: FlutterSemanticsAction = 64;
pub const FlutterSemanticsAction_kFlutterSemanticsActionDecrease: FlutterSemanticsAction = 128;
pub const FlutterSemanticsAction_kFlutterSemanticsActionShowOnScreen: FlutterSemanticsAction = 256;
pub const FlutterSemanticsAction_kFlutterSemanticsActionMoveCursorForwardByCharacter:
    FlutterSemanticsAction = 512;
pub const FlutterSemanticsAction_kFlutterSemanticsActionMoveCursorBackwardByCharacter:
    FlutterSemanticsAction = 1024;
pub const FlutterSemanticsAction_kFlutterSemanticsActionSetSelection: FlutterSemanticsAction = 2048;
pub const FlutterSemanticsAction_kFlutterSemanticsActionCopy: FlutterSemanticsAction = 4096;
pub const FlutterSemanticsAction_kFlutterSemanticsActionCut: FlutterSemanticsAction = 8192;
pub const FlutterSemanticsAction_kFlutterSemanticsActionPaste: FlutterSemanticsAction = 16384;
pub const FlutterSemanticsAction_kFlutterSemanticsActionDidGainAccessibilityFocus:
    FlutterSemanticsAction = 32768;
pub const FlutterSemanticsAction_kFlutterSemanticsActionDidLoseAccessibilityFocus:
    FlutterSemanticsAction = 65536;
pub const FlutterSemanticsAction_kFlutterSemanticsActionCustomAction: FlutterSemanticsAction =
    131072;
pub const FlutterSemanticsAction_kFlutterSemanticsActionDismiss: FlutterSemanticsAction = 262144;
pub const FlutterSemanticsAction_kFlutterSemanticsActionMoveCursorForwardByWord:
    FlutterSemanticsAction = 524288;
pub const FlutterSemanticsAction_kFlutterSemanticsActionMoveCursorBackwardByWord:
    FlutterSemanticsAction = 1048576;
pub const FlutterSemanticsAction_kFlutterSemanticsActionSetText: FlutterSemanticsAction = 2097152;
pub const FlutterSemanticsAction_kFlutterSemanticsActionFocus: FlutterSemanticsAction = 4194304;
pub const FlutterSemanticsAction_kFlutterSemanticsActionScrollToOffset: FlutterSemanticsAction =
    8388608;
pub const FlutterSemanticsAction_kFlutterSemanticsActionExpand: FlutterSemanticsAction = 16777216;
pub const FlutterSemanticsAction_kFlutterSemanticsActionCollapse: FlutterSemanticsAction = 33554432;
pub type FlutterSemanticsAction = ::std::os::raw::c_uint;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasCheckedState: FlutterSemanticsFlag = 1;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsChecked: FlutterSemanticsFlag = 2;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsSelected: FlutterSemanticsFlag = 4;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsButton: FlutterSemanticsFlag = 8;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsTextField: FlutterSemanticsFlag = 16;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsFocused: FlutterSemanticsFlag = 32;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasEnabledState: FlutterSemanticsFlag = 64;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsEnabled: FlutterSemanticsFlag = 128;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsInMutuallyExclusiveGroup:
    FlutterSemanticsFlag = 256;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsHeader: FlutterSemanticsFlag = 512;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsObscured: FlutterSemanticsFlag = 1024;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagScopesRoute: FlutterSemanticsFlag = 2048;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagNamesRoute: FlutterSemanticsFlag = 4096;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsHidden: FlutterSemanticsFlag = 8192;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsImage: FlutterSemanticsFlag = 16384;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsLiveRegion: FlutterSemanticsFlag = 32768;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasToggledState: FlutterSemanticsFlag = 65536;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsToggled: FlutterSemanticsFlag = 131072;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasImplicitScrolling: FlutterSemanticsFlag =
    262144;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsMultiline: FlutterSemanticsFlag = 524288;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsReadOnly: FlutterSemanticsFlag = 1048576;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsFocusable: FlutterSemanticsFlag = 2097152;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsLink: FlutterSemanticsFlag = 4194304;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsSlider: FlutterSemanticsFlag = 8388608;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsKeyboardKey: FlutterSemanticsFlag = 16777216;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsCheckStateMixed: FlutterSemanticsFlag =
    33554432;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasExpandedState: FlutterSemanticsFlag =
    67108864;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsExpanded: FlutterSemanticsFlag = 134217728;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasSelectedState: FlutterSemanticsFlag =
    268435456;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagHasRequiredState: FlutterSemanticsFlag =
    536870912;
pub const FlutterSemanticsFlag_kFlutterSemanticsFlagIsRequired: FlutterSemanticsFlag = 1073741824;
pub type FlutterSemanticsFlag = ::std::os::raw::c_uint;
pub const FlutterTristate_kFlutterTristateNone: FlutterTristate = 0;
pub const FlutterTristate_kFlutterTristateTrue: FlutterTristate = 1;
pub const FlutterTristate_kFlutterTristateFalse: FlutterTristate = 2;
pub type FlutterTristate = ::std::os::raw::c_uint;
pub const FlutterCheckState_kFlutterCheckStateNone: FlutterCheckState = 0;
pub const FlutterCheckState_kFlutterCheckStateTrue: FlutterCheckState = 1;
pub const FlutterCheckState_kFlutterCheckStateFalse: FlutterCheckState = 2;
pub const FlutterCheckState_kFlutterCheckStateMixed: FlutterCheckState = 3;
pub type FlutterCheckState = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsFlags {
    pub struct_size: usize,
    pub is_checked: FlutterCheckState,
    pub is_selected: FlutterTristate,
    pub is_enabled: FlutterTristate,
    pub is_toggled: FlutterTristate,
    pub is_expanded: FlutterTristate,
    pub is_required: FlutterTristate,
    pub is_focused: FlutterTristate,
    pub is_button: bool,
    pub is_text_field: bool,
    pub is_in_mutually_exclusive_group: bool,
    pub is_header: bool,
    pub is_obscured: bool,
    pub scopes_route: bool,
    pub names_route: bool,
    pub is_hidden: bool,
    pub is_image: bool,
    pub is_live_region: bool,
    pub has_implicit_scrolling: bool,
    pub is_multiline: bool,
    pub is_read_only: bool,
    pub is_link: bool,
    pub is_slider: bool,
    pub is_keyboard_key: bool,
    pub is_accessibility_focus_blocked: bool,
}
impl Default for FlutterSemanticsFlags {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterTextDirection_kFlutterTextDirectionUnknown: FlutterTextDirection = 0;
pub const FlutterTextDirection_kFlutterTextDirectionRTL: FlutterTextDirection = 1;
pub const FlutterTextDirection_kFlutterTextDirectionLTR: FlutterTextDirection = 2;
pub type FlutterTextDirection = ::std::os::raw::c_uint;
pub const FlutterThreadPriority_kBackground: FlutterThreadPriority = 0;
pub const FlutterThreadPriority_kNormal: FlutterThreadPriority = 1;
pub const FlutterThreadPriority_kDisplay: FlutterThreadPriority = 2;
pub const FlutterThreadPriority_kRaster: FlutterThreadPriority = 3;
pub type FlutterThreadPriority = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FlutterEngine {
    _unused: [u8; 0],
}
pub type FlutterEngine = *mut _FlutterEngine;
pub type FlutterViewId = i64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterTransformation {
    pub scaleX: f64,
    pub skewX: f64,
    pub transX: f64,
    pub skewY: f64,
    pub scaleY: f64,
    pub transY: f64,
    pub pers0: f64,
    pub pers1: f64,
    pub pers2: f64,
}
pub type VoidCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
pub const FlutterOpenGLTargetType_kFlutterOpenGLTargetTypeTexture: FlutterOpenGLTargetType = 0;
pub const FlutterOpenGLTargetType_kFlutterOpenGLTargetTypeFramebuffer: FlutterOpenGLTargetType = 1;
pub const FlutterOpenGLTargetType_kFlutterOpenGLTargetTypeSurface: FlutterOpenGLTargetType = 2;
pub type FlutterOpenGLTargetType = ::std::os::raw::c_uint;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatGray8: FlutterSoftwarePixelFormat =
    0;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatRGB565: FlutterSoftwarePixelFormat =
    1;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatRGBA4444:
    FlutterSoftwarePixelFormat = 2;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatRGBA8888:
    FlutterSoftwarePixelFormat = 3;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatRGBX8888:
    FlutterSoftwarePixelFormat = 4;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatBGRA8888:
    FlutterSoftwarePixelFormat = 5;
pub const FlutterSoftwarePixelFormat_kFlutterSoftwarePixelFormatNative32:
    FlutterSoftwarePixelFormat = 6;
pub type FlutterSoftwarePixelFormat = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterOpenGLTexture {
    pub target: u32,
    pub name: u32,
    pub format: u32,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
    pub width: usize,
    pub height: usize,
}
impl Default for FlutterOpenGLTexture {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterOpenGLFramebuffer {
    pub target: u32,
    pub name: u32,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
}
impl Default for FlutterOpenGLFramebuffer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterOpenGLSurfaceCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: *mut bool) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterOpenGLSurface {
    pub struct_size: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub make_current_callback: FlutterOpenGLSurfaceCallback,
    pub clear_current_callback: FlutterOpenGLSurfaceCallback,
    pub destruction_callback: VoidCallback,
    pub format: u32,
}
impl Default for FlutterOpenGLSurface {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type BoolCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> bool>;
pub type TransformationCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> FlutterTransformation,
>;
pub type UIntCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> u32>;
pub type SoftwareSurfacePresentCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_void,
        arg3: usize,
        arg4: usize,
    ) -> bool,
>;
pub type ProcResolver = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type TextureFrameCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: i64,
        arg3: usize,
        arg4: usize,
        arg5: *mut FlutterOpenGLTexture,
    ) -> bool,
>;
pub type VsyncCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: isize)>;
pub type OnPreEngineRestartCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void)>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterSize {
    pub width: f64,
    pub height: f64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterUIntSize {
    pub width: u32,
    pub height: u32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterRect {
    pub left: f64,
    pub top: f64,
    pub right: f64,
    pub bottom: f64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterPoint {
    pub x: f64,
    pub y: f64,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterRoundedRect {
    pub rect: FlutterRect,
    pub upper_left_corner_radius: FlutterSize,
    pub upper_right_corner_radius: FlutterSize,
    pub lower_right_corner_radius: FlutterSize,
    pub lower_left_corner_radius: FlutterSize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterDamage {
    pub struct_size: usize,
    pub num_rects: usize,
    pub damage: *mut FlutterRect,
}
impl Default for FlutterDamage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterFrameInfo {
    pub struct_size: usize,
    pub size: FlutterUIntSize,
}
pub type UIntFrameInfoCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: *const FlutterFrameInfo) -> u32,
>;
pub type FlutterFrameBufferWithDamageCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: isize, arg3: *mut FlutterDamage),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterPresentInfo {
    pub struct_size: usize,
    pub fbo_id: u32,
    pub frame_damage: FlutterDamage,
    pub buffer_damage: FlutterDamage,
}
impl Default for FlutterPresentInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type BoolPresentInfoCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const FlutterPresentInfo,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterOpenGLRendererConfig {
    pub struct_size: usize,
    pub make_current: BoolCallback,
    pub clear_current: BoolCallback,
    pub present: BoolCallback,
    pub fbo_callback: UIntCallback,
    pub make_resource_current: BoolCallback,
    pub fbo_reset_after_present: bool,
    pub surface_transformation: TransformationCallback,
    pub gl_proc_resolver: ProcResolver,
    pub gl_external_texture_frame_callback: TextureFrameCallback,
    pub fbo_with_frame_info_callback: UIntFrameInfoCallback,
    pub present_with_info: BoolPresentInfoCallback,
    pub populate_existing_damage: FlutterFrameBufferWithDamageCallback,
}
pub type FlutterMetalDeviceHandle = *const ::std::os::raw::c_void;
pub type FlutterMetalCommandQueueHandle = *const ::std::os::raw::c_void;
pub type FlutterMetalTextureHandle = *const ::std::os::raw::c_void;
pub const FlutterMetalExternalTexturePixelFormat_kYUVA: FlutterMetalExternalTexturePixelFormat = 0;
pub const FlutterMetalExternalTexturePixelFormat_kRGBA: FlutterMetalExternalTexturePixelFormat = 1;
pub type FlutterMetalExternalTexturePixelFormat = ::std::os::raw::c_uint;
pub const FlutterMetalExternalTextureYUVColorSpace_kBT601FullRange:
    FlutterMetalExternalTextureYUVColorSpace = 0;
pub const FlutterMetalExternalTextureYUVColorSpace_kBT601LimitedRange:
    FlutterMetalExternalTextureYUVColorSpace = 1;
pub type FlutterMetalExternalTextureYUVColorSpace = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterMetalExternalTexture {
    pub struct_size: usize,
    pub width: usize,
    pub height: usize,
    pub pixel_format: FlutterMetalExternalTexturePixelFormat,
    pub num_textures: usize,
    pub textures: *mut FlutterMetalTextureHandle,
    pub yuv_color_space: FlutterMetalExternalTextureYUVColorSpace,
}
impl Default for FlutterMetalExternalTexture {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterMetalTextureFrameCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: i64,
        arg3: usize,
        arg4: usize,
        arg5: *mut FlutterMetalExternalTexture,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterMetalTexture {
    pub struct_size: usize,
    pub texture_id: i64,
    pub texture: FlutterMetalTextureHandle,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
}
impl Default for FlutterMetalTexture {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterMetalTextureCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const FlutterFrameInfo,
    ) -> FlutterMetalTexture,
>;
pub type FlutterMetalPresentCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const FlutterMetalTexture,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterMetalRendererConfig {
    pub struct_size: usize,
    pub device: FlutterMetalDeviceHandle,
    pub present_command_queue: FlutterMetalCommandQueueHandle,
    pub get_next_drawable_callback: FlutterMetalTextureCallback,
    pub present_drawable_callback: FlutterMetalPresentCallback,
    pub external_texture_frame_callback: FlutterMetalTextureFrameCallback,
}
impl Default for FlutterMetalRendererConfig {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterVulkanInstanceHandle = *mut ::std::os::raw::c_void;
pub type FlutterVulkanPhysicalDeviceHandle = *mut ::std::os::raw::c_void;
pub type FlutterVulkanDeviceHandle = *mut ::std::os::raw::c_void;
pub type FlutterVulkanQueueHandle = *mut ::std::os::raw::c_void;
pub type FlutterVulkanImageHandle = u64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterVulkanImage {
    pub struct_size: usize,
    pub image: FlutterVulkanImageHandle,
    pub format: u32,
}
pub type FlutterVulkanInstanceProcAddressCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: FlutterVulkanInstanceHandle,
        arg3: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_void,
>;
pub type FlutterVulkanImageCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const FlutterFrameInfo,
    ) -> FlutterVulkanImage,
>;
pub type FlutterVulkanPresentCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut ::std::os::raw::c_void,
        arg2: *const FlutterVulkanImage,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterVulkanRendererConfig {
    pub struct_size: usize,
    pub version: u32,
    pub instance: FlutterVulkanInstanceHandle,
    pub physical_device: FlutterVulkanPhysicalDeviceHandle,
    pub device: FlutterVulkanDeviceHandle,
    pub queue_family_index: u32,
    pub queue: FlutterVulkanQueueHandle,
    pub enabled_instance_extension_count: usize,
    pub enabled_instance_extensions: *mut *const ::std::os::raw::c_char,
    pub enabled_device_extension_count: usize,
    pub enabled_device_extensions: *mut *const ::std::os::raw::c_char,
    pub get_instance_proc_address_callback: FlutterVulkanInstanceProcAddressCallback,
    pub get_next_image_callback: FlutterVulkanImageCallback,
    pub present_image_callback: FlutterVulkanPresentCallback,
}
impl Default for FlutterVulkanRendererConfig {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterSoftwareRendererConfig {
    pub struct_size: usize,
    pub surface_present_callback: SoftwareSurfacePresentCallback,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterRendererConfig {
    pub type_: FlutterRendererType,
    pub __bindgen_anon_1: FlutterRendererConfig__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterRendererConfig__bindgen_ty_1 {
    pub open_gl: FlutterOpenGLRendererConfig,
    pub software: FlutterSoftwareRendererConfig,
    pub metal: FlutterMetalRendererConfig,
    pub vulkan: FlutterVulkanRendererConfig,
}
impl Default for FlutterRendererConfig__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterRendererConfig {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterEngineDisplayId = u64;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterWindowMetricsEvent {
    pub struct_size: usize,
    pub width: usize,
    pub height: usize,
    pub pixel_ratio: f64,
    pub left: usize,
    pub top: usize,
    pub physical_view_inset_top: f64,
    pub physical_view_inset_right: f64,
    pub physical_view_inset_bottom: f64,
    pub physical_view_inset_left: f64,
    pub display_id: FlutterEngineDisplayId,
    pub view_id: i64,
    pub has_constraints: bool,
    pub min_width_constraint: usize,
    pub min_height_constraint: usize,
    pub max_width_constraint: usize,
    pub max_height_constraint: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterAddViewResult {
    pub struct_size: usize,
    pub added: bool,
    pub user_data: *mut ::std::os::raw::c_void,
}
impl Default for FlutterAddViewResult {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterAddViewCallback =
    ::std::option::Option<unsafe extern "C" fn(result: *const FlutterAddViewResult)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterAddViewInfo {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub view_metrics: *const FlutterWindowMetricsEvent,
    pub user_data: *mut ::std::os::raw::c_void,
    pub add_view_callback: FlutterAddViewCallback,
}
impl Default for FlutterAddViewInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterRemoveViewResult {
    pub struct_size: usize,
    pub removed: bool,
    pub user_data: *mut ::std::os::raw::c_void,
}
impl Default for FlutterRemoveViewResult {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterRemoveViewCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const FlutterRemoveViewResult)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterRemoveViewInfo {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub user_data: *mut ::std::os::raw::c_void,
    pub remove_view_callback: FlutterRemoveViewCallback,
}
impl Default for FlutterRemoveViewInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterViewFocusDirection_kUndefined: FlutterViewFocusDirection = 0;
pub const FlutterViewFocusDirection_kForward: FlutterViewFocusDirection = 1;
pub const FlutterViewFocusDirection_kBackward: FlutterViewFocusDirection = 2;
pub type FlutterViewFocusDirection = ::std::os::raw::c_uint;
pub const FlutterViewFocusState_kUnfocused: FlutterViewFocusState = 0;
pub const FlutterViewFocusState_kFocused: FlutterViewFocusState = 1;
pub type FlutterViewFocusState = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterViewFocusEvent {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub state: FlutterViewFocusState,
    pub direction: FlutterViewFocusDirection,
}
impl Default for FlutterViewFocusEvent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterViewFocusChangeRequest {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub state: FlutterViewFocusState,
    pub direction: FlutterViewFocusDirection,
}
impl Default for FlutterViewFocusChangeRequest {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterPointerPhase_kCancel: FlutterPointerPhase = 0;
pub const FlutterPointerPhase_kUp: FlutterPointerPhase = 1;
pub const FlutterPointerPhase_kDown: FlutterPointerPhase = 2;
pub const FlutterPointerPhase_kMove: FlutterPointerPhase = 3;
pub const FlutterPointerPhase_kAdd: FlutterPointerPhase = 4;
pub const FlutterPointerPhase_kRemove: FlutterPointerPhase = 5;
pub const FlutterPointerPhase_kHover: FlutterPointerPhase = 6;
pub const FlutterPointerPhase_kPanZoomStart: FlutterPointerPhase = 7;
pub const FlutterPointerPhase_kPanZoomUpdate: FlutterPointerPhase = 8;
pub const FlutterPointerPhase_kPanZoomEnd: FlutterPointerPhase = 9;
pub type FlutterPointerPhase = ::std::os::raw::c_uint;
pub const FlutterPointerDeviceKind_kFlutterPointerDeviceKindMouse: FlutterPointerDeviceKind = 1;
pub const FlutterPointerDeviceKind_kFlutterPointerDeviceKindTouch: FlutterPointerDeviceKind = 2;
pub const FlutterPointerDeviceKind_kFlutterPointerDeviceKindStylus: FlutterPointerDeviceKind = 3;
pub const FlutterPointerDeviceKind_kFlutterPointerDeviceKindTrackpad: FlutterPointerDeviceKind = 4;
pub const FlutterPointerDeviceKind_kFlutterPointerDeviceKindInvertedStylus:
    FlutterPointerDeviceKind = 5;
pub type FlutterPointerDeviceKind = ::std::os::raw::c_uint;
pub const FlutterPointerMouseButtons_kFlutterPointerButtonMousePrimary: FlutterPointerMouseButtons =
    1;
pub const FlutterPointerMouseButtons_kFlutterPointerButtonMouseSecondary:
    FlutterPointerMouseButtons = 2;
pub const FlutterPointerMouseButtons_kFlutterPointerButtonMouseMiddle: FlutterPointerMouseButtons =
    4;
pub const FlutterPointerMouseButtons_kFlutterPointerButtonMouseBack: FlutterPointerMouseButtons = 8;
pub const FlutterPointerMouseButtons_kFlutterPointerButtonMouseForward: FlutterPointerMouseButtons =
    16;
pub type FlutterPointerMouseButtons = ::std::os::raw::c_uint;
pub const FlutterPointerStylusButtons_kFlutterPointerButtonStylusContact:
    FlutterPointerStylusButtons = 1;
pub const FlutterPointerStylusButtons_kFlutterPointerButtonStylusPrimary:
    FlutterPointerStylusButtons = 2;
pub const FlutterPointerStylusButtons_kFlutterPointerButtonStylusSecondary:
    FlutterPointerStylusButtons = 4;
pub type FlutterPointerStylusButtons = ::std::os::raw::c_uint;
pub const FlutterPointerSignalKind_kFlutterPointerSignalKindNone: FlutterPointerSignalKind = 0;
pub const FlutterPointerSignalKind_kFlutterPointerSignalKindScroll: FlutterPointerSignalKind = 1;
pub const FlutterPointerSignalKind_kFlutterPointerSignalKindScrollInertiaCancel:
    FlutterPointerSignalKind = 2;
pub const FlutterPointerSignalKind_kFlutterPointerSignalKindScale: FlutterPointerSignalKind = 3;
pub type FlutterPointerSignalKind = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterPointerEvent {
    pub struct_size: usize,
    pub phase: FlutterPointerPhase,
    pub timestamp: usize,
    pub x: f64,
    pub y: f64,
    pub device: i32,
    pub signal_kind: FlutterPointerSignalKind,
    pub scroll_delta_x: f64,
    pub scroll_delta_y: f64,
    pub device_kind: FlutterPointerDeviceKind,
    pub buttons: i64,
    pub pan_x: f64,
    pub pan_y: f64,
    pub scale: f64,
    pub rotation: f64,
    pub view_id: FlutterViewId,
    pub pressure: f64,
    pub pressure_min: f64,
    pub pressure_max: f64,
}
impl Default for FlutterPointerEvent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterKeyEventType_kFlutterKeyEventTypeUp: FlutterKeyEventType = 1;
pub const FlutterKeyEventType_kFlutterKeyEventTypeDown: FlutterKeyEventType = 2;
pub const FlutterKeyEventType_kFlutterKeyEventTypeRepeat: FlutterKeyEventType = 3;
pub type FlutterKeyEventType = ::std::os::raw::c_uint;
pub const FlutterKeyEventDeviceType_kFlutterKeyEventDeviceTypeKeyboard: FlutterKeyEventDeviceType =
    1;
pub const FlutterKeyEventDeviceType_kFlutterKeyEventDeviceTypeDirectionalPad:
    FlutterKeyEventDeviceType = 2;
pub const FlutterKeyEventDeviceType_kFlutterKeyEventDeviceTypeGamepad: FlutterKeyEventDeviceType =
    3;
pub const FlutterKeyEventDeviceType_kFlutterKeyEventDeviceTypeJoystick: FlutterKeyEventDeviceType =
    4;
pub const FlutterKeyEventDeviceType_kFlutterKeyEventDeviceTypeHdmi: FlutterKeyEventDeviceType = 5;
pub type FlutterKeyEventDeviceType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterKeyEvent {
    pub struct_size: usize,
    pub timestamp: f64,
    pub type_: FlutterKeyEventType,
    pub physical: u64,
    pub logical: u64,
    pub character: *const ::std::os::raw::c_char,
    pub synthesized: bool,
    pub device_type: FlutterKeyEventDeviceType,
}
impl Default for FlutterKeyEvent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterKeyEventCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: bool, arg2: *mut ::std::os::raw::c_void)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FlutterPlatformMessageResponseHandle {
    _unused: [u8; 0],
}
pub type FlutterPlatformMessageResponseHandle = _FlutterPlatformMessageResponseHandle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterPlatformMessage {
    pub struct_size: usize,
    pub channel: *const ::std::os::raw::c_char,
    pub message: *const u8,
    pub message_size: usize,
    pub response_handle: *const FlutterPlatformMessageResponseHandle,
}
impl Default for FlutterPlatformMessage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterPlatformMessageCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const FlutterPlatformMessage, arg2: *mut ::std::os::raw::c_void),
>;
pub type FlutterDataCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const u8, arg2: usize, arg3: *mut ::std::os::raw::c_void),
>;
pub type FlutterPlatformViewIdentifier = i64;
pub const FlutterStringAttributeType_kSpellOut: FlutterStringAttributeType = 0;
pub const FlutterStringAttributeType_kLocale: FlutterStringAttributeType = 1;
pub type FlutterStringAttributeType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterSpellOutStringAttribute {
    pub struct_size: usize,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterLocaleStringAttribute {
    pub struct_size: usize,
    pub locale: *const ::std::os::raw::c_char,
}
impl Default for FlutterLocaleStringAttribute {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterStringAttribute {
    pub struct_size: usize,
    pub start: usize,
    pub end: usize,
    pub type_: FlutterStringAttributeType,
    pub __bindgen_anon_1: FlutterStringAttribute__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterStringAttribute__bindgen_ty_1 {
    pub spell_out: *const FlutterSpellOutStringAttribute,
    pub locale: *const FlutterLocaleStringAttribute,
}
impl Default for FlutterStringAttribute__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterStringAttribute {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsNode {
    pub struct_size: usize,
    pub id: i32,
    pub flags: FlutterSemanticsFlag,
    pub actions: FlutterSemanticsAction,
    pub text_selection_base: i32,
    pub text_selection_extent: i32,
    pub scroll_child_count: i32,
    pub scroll_index: i32,
    pub scroll_position: f64,
    pub scroll_extent_max: f64,
    pub scroll_extent_min: f64,
    pub elevation: f64,
    pub thickness: f64,
    pub label: *const ::std::os::raw::c_char,
    pub hint: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
    pub increased_value: *const ::std::os::raw::c_char,
    pub decreased_value: *const ::std::os::raw::c_char,
    pub text_direction: FlutterTextDirection,
    pub rect: FlutterRect,
    pub transform: FlutterTransformation,
    pub child_count: usize,
    pub children_in_traversal_order: *const i32,
    pub children_in_hit_test_order: *const i32,
    pub custom_accessibility_actions_count: usize,
    pub custom_accessibility_actions: *const i32,
    pub platform_view_id: FlutterPlatformViewIdentifier,
    pub tooltip: *const ::std::os::raw::c_char,
    pub heading_level: i32,
}
impl Default for FlutterSemanticsNode {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsNode2 {
    pub struct_size: usize,
    pub id: i32,
    pub flags__deprecated__: FlutterSemanticsFlag,
    pub actions: FlutterSemanticsAction,
    pub text_selection_base: i32,
    pub text_selection_extent: i32,
    pub scroll_child_count: i32,
    pub scroll_index: i32,
    pub scroll_position: f64,
    pub scroll_extent_max: f64,
    pub scroll_extent_min: f64,
    pub elevation: f64,
    pub thickness: f64,
    pub label: *const ::std::os::raw::c_char,
    pub hint: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
    pub increased_value: *const ::std::os::raw::c_char,
    pub decreased_value: *const ::std::os::raw::c_char,
    pub text_direction: FlutterTextDirection,
    pub rect: FlutterRect,
    pub transform: FlutterTransformation,
    pub child_count: usize,
    pub children_in_traversal_order: *const i32,
    pub children_in_hit_test_order: *const i32,
    pub custom_accessibility_actions_count: usize,
    pub custom_accessibility_actions: *const i32,
    pub platform_view_id: FlutterPlatformViewIdentifier,
    pub tooltip: *const ::std::os::raw::c_char,
    pub label_attribute_count: usize,
    pub label_attributes: *mut *const FlutterStringAttribute,
    pub hint_attribute_count: usize,
    pub hint_attributes: *mut *const FlutterStringAttribute,
    pub value_attribute_count: usize,
    pub value_attributes: *mut *const FlutterStringAttribute,
    pub increased_value_attribute_count: usize,
    pub increased_value_attributes: *mut *const FlutterStringAttribute,
    pub decreased_value_attribute_count: usize,
    pub decreased_value_attributes: *mut *const FlutterStringAttribute,
    pub flags2: *mut FlutterSemanticsFlags,
    pub heading_level: i32,
    pub identifier: *const ::std::os::raw::c_char,
}
impl Default for FlutterSemanticsNode2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsCustomAction {
    pub struct_size: usize,
    pub id: i32,
    pub override_action: FlutterSemanticsAction,
    pub label: *const ::std::os::raw::c_char,
    pub hint: *const ::std::os::raw::c_char,
}
impl Default for FlutterSemanticsCustomAction {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsCustomAction2 {
    pub struct_size: usize,
    pub id: i32,
    pub override_action: FlutterSemanticsAction,
    pub label: *const ::std::os::raw::c_char,
    pub hint: *const ::std::os::raw::c_char,
}
impl Default for FlutterSemanticsCustomAction2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsUpdate {
    pub struct_size: usize,
    pub nodes_count: usize,
    pub nodes: *mut FlutterSemanticsNode,
    pub custom_actions_count: usize,
    pub custom_actions: *mut FlutterSemanticsCustomAction,
}
impl Default for FlutterSemanticsUpdate {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSemanticsUpdate2 {
    pub struct_size: usize,
    pub node_count: usize,
    pub nodes: *mut *mut FlutterSemanticsNode2,
    pub custom_action_count: usize,
    pub custom_actions: *mut *mut FlutterSemanticsCustomAction2,
    pub view_id: FlutterViewId,
}
impl Default for FlutterSemanticsUpdate2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterUpdateSemanticsNodeCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const FlutterSemanticsNode, arg2: *mut ::std::os::raw::c_void),
>;
pub type FlutterUpdateSemanticsCustomActionCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const FlutterSemanticsCustomAction,
        arg2: *mut ::std::os::raw::c_void,
    ),
>;
pub type FlutterUpdateSemanticsCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const FlutterSemanticsUpdate, arg2: *mut ::std::os::raw::c_void),
>;
pub type FlutterUpdateSemanticsCallback2 = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const FlutterSemanticsUpdate2, arg2: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterChannelUpdate {
    pub struct_size: usize,
    pub channel: *const ::std::os::raw::c_char,
    pub listening: bool,
}
impl Default for FlutterChannelUpdate {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterChannelUpdateCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *const FlutterChannelUpdate, arg2: *mut ::std::os::raw::c_void),
>;
pub type FlutterViewFocusChangeRequestCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const FlutterViewFocusChangeRequest,
        arg2: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FlutterTaskRunner {
    _unused: [u8; 0],
}
pub type FlutterTaskRunner = *mut _FlutterTaskRunner;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterTask {
    pub runner: FlutterTaskRunner,
    pub task: u64,
}
impl Default for FlutterTask {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterTaskRunnerPostTaskCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: FlutterTask, arg2: u64, arg3: *mut ::std::os::raw::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterTaskRunnerDescription {
    pub struct_size: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub runs_task_on_current_thread_callback: BoolCallback,
    pub post_task_callback: FlutterTaskRunnerPostTaskCallback,
    pub identifier: usize,
    pub destruction_callback: VoidCallback,
}
impl Default for FlutterTaskRunnerDescription {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterCustomTaskRunners {
    pub struct_size: usize,
    pub platform_task_runner: *const FlutterTaskRunnerDescription,
    pub render_task_runner: *const FlutterTaskRunnerDescription,
    pub thread_priority_setter:
        ::std::option::Option<unsafe extern "C" fn(arg1: FlutterThreadPriority)>,
    pub ui_task_runner: *const FlutterTaskRunnerDescription,
}
impl Default for FlutterCustomTaskRunners {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterOpenGLBackingStore {
    pub type_: FlutterOpenGLTargetType,
    pub __bindgen_anon_1: FlutterOpenGLBackingStore__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterOpenGLBackingStore__bindgen_ty_1 {
    pub texture: FlutterOpenGLTexture,
    pub framebuffer: FlutterOpenGLFramebuffer,
    pub surface: FlutterOpenGLSurface,
}
impl Default for FlutterOpenGLBackingStore__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterOpenGLBackingStore {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSoftwareBackingStore {
    pub allocation: *const ::std::os::raw::c_void,
    pub row_bytes: usize,
    pub height: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
}
impl Default for FlutterSoftwareBackingStore {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSoftwareBackingStore2 {
    pub struct_size: usize,
    pub allocation: *const ::std::os::raw::c_void,
    pub row_bytes: usize,
    pub height: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
    pub pixel_format: FlutterSoftwarePixelFormat,
}
impl Default for FlutterSoftwareBackingStore2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterMetalBackingStore {
    pub struct_size: usize,
    pub __bindgen_anon_1: FlutterMetalBackingStore__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterMetalBackingStore__bindgen_ty_1 {
    pub texture: FlutterMetalTexture,
}
impl Default for FlutterMetalBackingStore__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterMetalBackingStore {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterVulkanBackingStore {
    pub struct_size: usize,
    pub image: *const FlutterVulkanImage,
    pub user_data: *mut ::std::os::raw::c_void,
    pub destruction_callback: VoidCallback,
}
impl Default for FlutterVulkanBackingStore {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterPlatformViewMutationType_kFlutterPlatformViewMutationTypeOpacity:
    FlutterPlatformViewMutationType = 0;
pub const FlutterPlatformViewMutationType_kFlutterPlatformViewMutationTypeClipRect:
    FlutterPlatformViewMutationType = 1;
pub const FlutterPlatformViewMutationType_kFlutterPlatformViewMutationTypeClipRoundedRect:
    FlutterPlatformViewMutationType = 2;
pub const FlutterPlatformViewMutationType_kFlutterPlatformViewMutationTypeTransformation:
    FlutterPlatformViewMutationType = 3;
pub type FlutterPlatformViewMutationType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterPlatformViewMutation {
    pub type_: FlutterPlatformViewMutationType,
    pub __bindgen_anon_1: FlutterPlatformViewMutation__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterPlatformViewMutation__bindgen_ty_1 {
    pub opacity: f64,
    pub clip_rect: FlutterRect,
    pub clip_rounded_rect: FlutterRoundedRect,
    pub transformation: FlutterTransformation,
}
impl Default for FlutterPlatformViewMutation__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterPlatformViewMutation {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterPlatformView {
    pub struct_size: usize,
    pub identifier: FlutterPlatformViewIdentifier,
    pub mutations_count: usize,
    pub mutations: *mut *const FlutterPlatformViewMutation,
}
impl Default for FlutterPlatformView {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterBackingStoreType_kFlutterBackingStoreTypeOpenGL: FlutterBackingStoreType = 0;
pub const FlutterBackingStoreType_kFlutterBackingStoreTypeSoftware: FlutterBackingStoreType = 1;
pub const FlutterBackingStoreType_kFlutterBackingStoreTypeMetal: FlutterBackingStoreType = 2;
pub const FlutterBackingStoreType_kFlutterBackingStoreTypeVulkan: FlutterBackingStoreType = 3;
pub const FlutterBackingStoreType_kFlutterBackingStoreTypeSoftware2: FlutterBackingStoreType = 4;
pub type FlutterBackingStoreType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterBackingStore {
    pub struct_size: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub type_: FlutterBackingStoreType,
    pub did_update: bool,
    pub __bindgen_anon_1: FlutterBackingStore__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterBackingStore__bindgen_ty_1 {
    pub open_gl: FlutterOpenGLBackingStore,
    pub software: FlutterSoftwareBackingStore,
    pub software2: FlutterSoftwareBackingStore2,
    pub metal: FlutterMetalBackingStore,
    pub vulkan: FlutterVulkanBackingStore,
}
impl Default for FlutterBackingStore__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterBackingStore {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterBackingStoreConfig {
    pub struct_size: usize,
    pub size: FlutterSize,
    pub view_id: FlutterViewId,
}
pub const FlutterLayerContentType_kFlutterLayerContentTypeBackingStore: FlutterLayerContentType = 0;
pub const FlutterLayerContentType_kFlutterLayerContentTypePlatformView: FlutterLayerContentType = 1;
pub type FlutterLayerContentType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterRegion {
    pub struct_size: usize,
    pub rects_count: usize,
    pub rects: *mut FlutterRect,
}
impl Default for FlutterRegion {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterBackingStorePresentInfo {
    pub struct_size: usize,
    pub paint_region: *mut FlutterRegion,
}
impl Default for FlutterBackingStorePresentInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterLayer {
    pub struct_size: usize,
    pub type_: FlutterLayerContentType,
    pub __bindgen_anon_1: FlutterLayer__bindgen_ty_1,
    pub offset: FlutterPoint,
    pub size: FlutterSize,
    pub backing_store_present_info: *mut FlutterBackingStorePresentInfo,
    pub presentation_time: u64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterLayer__bindgen_ty_1 {
    pub backing_store: *const FlutterBackingStore,
    pub platform_view: *const FlutterPlatformView,
}
impl Default for FlutterLayer__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterLayer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterPresentViewInfo {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub layers: *mut *const FlutterLayer,
    pub layers_count: usize,
    pub user_data: *mut ::std::os::raw::c_void,
}
impl Default for FlutterPresentViewInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterBackingStoreCreateCallback = ::std::option::Option<
    unsafe extern "C" fn(
        config: *const FlutterBackingStoreConfig,
        backing_store_out: *mut FlutterBackingStore,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type FlutterBackingStoreCollectCallback = ::std::option::Option<
    unsafe extern "C" fn(
        renderer: *const FlutterBackingStore,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type FlutterLayersPresentCallback = ::std::option::Option<
    unsafe extern "C" fn(
        layers: *mut *const FlutterLayer,
        layers_count: usize,
        user_data: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type FlutterPresentViewCallback =
    ::std::option::Option<unsafe extern "C" fn(arg1: *const FlutterPresentViewInfo) -> bool>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterCompositor {
    pub struct_size: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub create_backing_store_callback: FlutterBackingStoreCreateCallback,
    pub collect_backing_store_callback: FlutterBackingStoreCollectCallback,
    pub present_layers_callback: FlutterLayersPresentCallback,
    pub avoid_backing_store_cache: bool,
    pub present_view_callback: FlutterPresentViewCallback,
}
impl Default for FlutterCompositor {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterLocale {
    pub struct_size: usize,
    pub language_code: *const ::std::os::raw::c_char,
    pub country_code: *const ::std::os::raw::c_char,
    pub script_code: *const ::std::os::raw::c_char,
    pub variant_code: *const ::std::os::raw::c_char,
}
impl Default for FlutterLocale {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterComputePlatformResolvedLocaleCallback = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut *const FlutterLocale, arg2: usize) -> *const FlutterLocale,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterEngineDisplay {
    pub struct_size: usize,
    pub display_id: FlutterEngineDisplayId,
    pub single_display: bool,
    pub refresh_rate: f64,
    pub width: usize,
    pub height: usize,
    pub device_pixel_ratio: f64,
}
pub const FlutterEngineDisplaysUpdateType_kFlutterEngineDisplaysUpdateTypeStartup:
    FlutterEngineDisplaysUpdateType = 0;
pub const FlutterEngineDisplaysUpdateType_kFlutterEngineDisplaysUpdateTypeCount:
    FlutterEngineDisplaysUpdateType = 1;
pub type FlutterEngineDisplaysUpdateType = ::std::os::raw::c_uint;
pub type FlutterEngineDartPort = i64;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeNull:
    FlutterEngineDartObjectType = 0;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeBool:
    FlutterEngineDartObjectType = 1;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeInt32:
    FlutterEngineDartObjectType = 2;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeInt64:
    FlutterEngineDartObjectType = 3;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeDouble:
    FlutterEngineDartObjectType = 4;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeString:
    FlutterEngineDartObjectType = 5;
pub const FlutterEngineDartObjectType_kFlutterEngineDartObjectTypeBuffer:
    FlutterEngineDartObjectType = 6;
pub type FlutterEngineDartObjectType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterEngineDartBuffer {
    pub struct_size: usize,
    pub user_data: *mut ::std::os::raw::c_void,
    pub buffer_collect_callback: VoidCallback,
    pub buffer: *mut u8,
    pub buffer_size: usize,
}
impl Default for FlutterEngineDartBuffer {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterEngineDartObject {
    pub type_: FlutterEngineDartObjectType,
    pub __bindgen_anon_1: FlutterEngineDartObject__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterEngineDartObject__bindgen_ty_1 {
    pub bool_value: bool,
    pub int32_value: i32,
    pub int64_value: i64,
    pub double_value: f64,
    pub string_value: *const ::std::os::raw::c_char,
    pub buffer_value: *const FlutterEngineDartBuffer,
}
impl Default for FlutterEngineDartObject__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterEngineDartObject {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const FlutterNativeThreadType_kFlutterNativeThreadTypePlatform: FlutterNativeThreadType = 0;
pub const FlutterNativeThreadType_kFlutterNativeThreadTypeRender: FlutterNativeThreadType = 1;
pub const FlutterNativeThreadType_kFlutterNativeThreadTypeUI: FlutterNativeThreadType = 2;
pub const FlutterNativeThreadType_kFlutterNativeThreadTypeWorker: FlutterNativeThreadType = 3;
pub type FlutterNativeThreadType = ::std::os::raw::c_uint;
pub type FlutterNativeThreadCallback = ::std::option::Option<
    unsafe extern "C" fn(type_: FlutterNativeThreadType, user_data: *mut ::std::os::raw::c_void),
>;
pub const FlutterEngineAOTDataSourceType_kFlutterEngineAOTDataSourceTypeElfPath:
    FlutterEngineAOTDataSourceType = 0;
pub type FlutterEngineAOTDataSourceType = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct FlutterEngineAOTDataSource {
    pub type_: FlutterEngineAOTDataSourceType,
    pub __bindgen_anon_1: FlutterEngineAOTDataSource__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union FlutterEngineAOTDataSource__bindgen_ty_1 {
    pub elf_path: *const ::std::os::raw::c_char,
}
impl Default for FlutterEngineAOTDataSource__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for FlutterEngineAOTDataSource {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FlutterLogMessageCallback = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const ::std::os::raw::c_char,
        arg2: *const ::std::os::raw::c_char,
        arg3: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _FlutterEngineAOTData {
    _unused: [u8; 0],
}
pub type FlutterEngineAOTData = *mut _FlutterEngineAOTData;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterProjectArgs {
    pub struct_size: usize,
    pub assets_path: *const ::std::os::raw::c_char,
    pub main_path__unused__: *const ::std::os::raw::c_char,
    pub packages_path__unused__: *const ::std::os::raw::c_char,
    pub icu_data_path: *const ::std::os::raw::c_char,
    pub command_line_argc: ::std::os::raw::c_int,
    pub command_line_argv: *const *const ::std::os::raw::c_char,
    pub platform_message_callback: FlutterPlatformMessageCallback,
    pub vm_snapshot_data: *const u8,
    pub vm_snapshot_data_size: usize,
    pub vm_snapshot_instructions: *const u8,
    pub vm_snapshot_instructions_size: usize,
    pub isolate_snapshot_data: *const u8,
    pub isolate_snapshot_data_size: usize,
    pub isolate_snapshot_instructions: *const u8,
    pub isolate_snapshot_instructions_size: usize,
    pub root_isolate_create_callback: VoidCallback,
    pub update_semantics_node_callback: FlutterUpdateSemanticsNodeCallback,
    pub update_semantics_custom_action_callback: FlutterUpdateSemanticsCustomActionCallback,
    pub persistent_cache_path: *const ::std::os::raw::c_char,
    pub is_persistent_cache_read_only: bool,
    pub vsync_callback: VsyncCallback,
    pub custom_dart_entrypoint: *const ::std::os::raw::c_char,
    pub custom_task_runners: *const FlutterCustomTaskRunners,
    pub shutdown_dart_vm_when_done: bool,
    pub compositor: *const FlutterCompositor,
    pub dart_old_gen_heap_size: i64,
    pub aot_data: FlutterEngineAOTData,
    pub compute_platform_resolved_locale_callback: FlutterComputePlatformResolvedLocaleCallback,
    pub dart_entrypoint_argc: ::std::os::raw::c_int,
    pub dart_entrypoint_argv: *const *const ::std::os::raw::c_char,
    pub log_message_callback: FlutterLogMessageCallback,
    pub log_tag: *const ::std::os::raw::c_char,
    pub on_pre_engine_restart_callback: OnPreEngineRestartCallback,
    pub update_semantics_callback: FlutterUpdateSemanticsCallback,
    pub update_semantics_callback2: FlutterUpdateSemanticsCallback2,
    pub channel_update_callback: FlutterChannelUpdateCallback,
    pub view_focus_change_request_callback: FlutterViewFocusChangeRequestCallback,
    pub engine_id: i64,
    pub enable_wide_gamut: bool,
}
impl Default for FlutterProjectArgs {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FlutterSendSemanticsActionInfo {
    pub struct_size: usize,
    pub view_id: FlutterViewId,
    pub node_id: u64,
    pub action: FlutterSemanticsAction,
    pub data: *const u8,
    pub data_length: usize,
}
impl Default for FlutterSendSemanticsActionInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn FlutterEngineCreateAOTData(
        source: *const FlutterEngineAOTDataSource,
        data_out: *mut FlutterEngineAOTData,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineCollectAOTData(data: FlutterEngineAOTData) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineRun(
        version: usize,
        config: *const FlutterRendererConfig,
        args: *const FlutterProjectArgs,
        user_data: *mut ::std::os::raw::c_void,
        engine_out: *mut FlutterEngine,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineShutdown(engine: FlutterEngine) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineInitialize(
        version: usize,
        config: *const FlutterRendererConfig,
        args: *const FlutterProjectArgs,
        user_data: *mut ::std::os::raw::c_void,
        engine_out: *mut FlutterEngine,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineDeinitialize(engine: FlutterEngine) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineRunInitialized(engine: FlutterEngine) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineAddView(
        engine: FlutterEngine,
        info: *const FlutterAddViewInfo,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineRemoveView(
        engine: FlutterEngine,
        info: *const FlutterRemoveViewInfo,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendViewFocusEvent(
        engine: FlutterEngine,
        event: *const FlutterViewFocusEvent,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendWindowMetricsEvent(
        engine: FlutterEngine,
        event: *const FlutterWindowMetricsEvent,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendPointerEvent(
        engine: FlutterEngine,
        events: *const FlutterPointerEvent,
        events_count: usize,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendKeyEvent(
        engine: FlutterEngine,
        event: *const FlutterKeyEvent,
        callback: FlutterKeyEventCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendPlatformMessage(
        engine: FlutterEngine,
        message: *const FlutterPlatformMessage,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendPlatformMessageResponse(
        engine: FlutterEngine,
        handle: *const FlutterPlatformMessageResponseHandle,
        data: *const u8,
        data_length: usize,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineRegisterExternalTexture(
        engine: FlutterEngine,
        texture_identifier: i64,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineUnregisterExternalTexture(
        engine: FlutterEngine,
        texture_identifier: i64,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineMarkExternalTextureFrameAvailable(
        engine: FlutterEngine,
        texture_identifier: i64,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineUpdateSemanticsEnabled(
        engine: FlutterEngine,
        enabled: bool,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineUpdateAccessibilityFeatures(
        engine: FlutterEngine,
        features: FlutterAccessibilityFeature,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineDispatchSemanticsAction(
        engine: FlutterEngine,
        node_id: u64,
        action: FlutterSemanticsAction,
        data: *const u8,
        data_length: usize,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineSendSemanticsAction(
        engine: FlutterEngine,
        info: *const FlutterSendSemanticsActionInfo,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineOnVsync(
        engine: FlutterEngine,
        baton: isize,
        frame_start_time_nanos: u64,
        frame_target_time_nanos: u64,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineReloadSystemFonts(engine: FlutterEngine) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineTraceEventDurationBegin(name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn FlutterEngineTraceEventDurationEnd(name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn FlutterEngineTraceEventInstant(name: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn FlutterEnginePostRenderThreadTask(
        engine: FlutterEngine,
        callback: VoidCallback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineGetCurrentTime() -> u64;
}
unsafe extern "C" {
    pub fn FlutterEngineRunTask(
        engine: FlutterEngine,
        task: *const FlutterTask,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineUpdateLocales(
        engine: FlutterEngine,
        locales: *mut *const FlutterLocale,
        locales_count: usize,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineRunsAOTCompiledDartCode() -> bool;
}
unsafe extern "C" {
    pub fn FlutterEnginePostDartObject(
        engine: FlutterEngine,
        port: FlutterEngineDartPort,
        object: *const FlutterEngineDartObject,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineNotifyLowMemoryWarning(engine: FlutterEngine) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEnginePostCallbackOnAllNativeThreads(
        engine: FlutterEngine,
        callback: FlutterNativeThreadCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineNotifyDisplayUpdate(
        engine: FlutterEngine,
        update_type: FlutterEngineDisplaysUpdateType,
        displays: *const FlutterEngineDisplay,
        display_count: usize,
    ) -> FlutterEngineResult;
}
unsafe extern "C" {
    pub fn FlutterEngineScheduleFrame(engine: FlutterEngine) -> FlutterEngineResult;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DenialFlutterRenderOutput {
    pub struct_size: usize,
    pub render_view_id: i64,
    pub configuration_generation: u64,
    pub source_physical_x: f64,
    pub source_physical_y: f64,
    pub source_physical_width: f64,
    pub source_physical_height: f64,
    pub target_width: usize,
    pub target_height: usize,
    pub scale_120: u32,
    pub source_to_target_transform: FlutterTransformation,
}
pub type DenialFlutterExternalTextureGlStateCallback = ::std::option::Option<
    unsafe extern "C" fn(user_data: *mut ::std::os::raw::c_void, texture_identifier: i64) -> bool,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct DenialFlutterExternalTexturePresentation {
    pub struct_size: usize,
    pub width: f64,
    pub height: f64,
    pub source: [f64; 4usize],
    pub destination: [f64; 4usize],
    pub background: [f64; 4usize],
    pub background_argb: u32,
}
pub type DenialFlutterExternalTexturePresentationCallback = ::std::option::Option<
    unsafe extern "C" fn(
        user_data: *mut ::std::os::raw::c_void,
        texture_identifier: i64,
        presentation: *mut DenialFlutterExternalTexturePresentation,
    ) -> bool,
>;
unsafe extern "C" {
    pub fn FlutterEngineSetNextFrameCallback(
        engine: FlutterEngine,
        callback: VoidCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult;
}
pub type FlutterEngineCreateAOTDataFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        source: *const FlutterEngineAOTDataSource,
        data_out: *mut FlutterEngineAOTData,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineCollectAOTDataFnPtr =
    ::std::option::Option<unsafe extern "C" fn(data: FlutterEngineAOTData) -> FlutterEngineResult>;
pub type FlutterEngineRunFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        version: usize,
        config: *const FlutterRendererConfig,
        args: *const FlutterProjectArgs,
        user_data: *mut ::std::os::raw::c_void,
        engine_out: *mut FlutterEngine,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineShutdownFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEngineInitializeFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        version: usize,
        config: *const FlutterRendererConfig,
        args: *const FlutterProjectArgs,
        user_data: *mut ::std::os::raw::c_void,
        engine_out: *mut FlutterEngine,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineDeinitializeFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEngineRunInitializedFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEngineSendWindowMetricsEventFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        event: *const FlutterWindowMetricsEvent,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendPointerEventFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        events: *const FlutterPointerEvent,
        events_count: usize,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendKeyEventFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        event: *const FlutterKeyEvent,
        callback: FlutterKeyEventCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendPlatformMessageFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        message: *const FlutterPlatformMessage,
    ) -> FlutterEngineResult,
>;
pub type FlutterEnginePlatformMessageCreateResponseHandleFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        data_callback: FlutterDataCallback,
        user_data: *mut ::std::os::raw::c_void,
        response_out: *mut *mut FlutterPlatformMessageResponseHandle,
    ) -> FlutterEngineResult,
>;
pub type FlutterEnginePlatformMessageReleaseResponseHandleFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        response: *mut FlutterPlatformMessageResponseHandle,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendPlatformMessageResponseFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        handle: *const FlutterPlatformMessageResponseHandle,
        data: *const u8,
        data_length: usize,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineRegisterExternalTextureFnPtr = ::std::option::Option<
    unsafe extern "C" fn(engine: FlutterEngine, texture_identifier: i64) -> FlutterEngineResult,
>;
pub type FlutterEngineUnregisterExternalTextureFnPtr = ::std::option::Option<
    unsafe extern "C" fn(engine: FlutterEngine, texture_identifier: i64) -> FlutterEngineResult,
>;
pub type FlutterEngineMarkExternalTextureFrameAvailableFnPtr = ::std::option::Option<
    unsafe extern "C" fn(engine: FlutterEngine, texture_identifier: i64) -> FlutterEngineResult,
>;
pub type FlutterEngineUpdateSemanticsEnabledFnPtr = ::std::option::Option<
    unsafe extern "C" fn(engine: FlutterEngine, enabled: bool) -> FlutterEngineResult,
>;
pub type FlutterEngineUpdateAccessibilityFeaturesFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        features: FlutterAccessibilityFeature,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineDispatchSemanticsActionFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        id: u64,
        action: FlutterSemanticsAction,
        data: *const u8,
        data_length: usize,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendSemanticsActionFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        info: *const FlutterSendSemanticsActionInfo,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineOnVsyncFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        baton: isize,
        frame_start_time_nanos: u64,
        frame_target_time_nanos: u64,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineReloadSystemFontsFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEngineTraceEventDurationBeginFnPtr =
    ::std::option::Option<unsafe extern "C" fn(name: *const ::std::os::raw::c_char)>;
pub type FlutterEngineTraceEventDurationEndFnPtr =
    ::std::option::Option<unsafe extern "C" fn(name: *const ::std::os::raw::c_char)>;
pub type FlutterEngineTraceEventInstantFnPtr =
    ::std::option::Option<unsafe extern "C" fn(name: *const ::std::os::raw::c_char)>;
pub type FlutterEnginePostRenderThreadTaskFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        callback: VoidCallback,
        callback_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineGetCurrentTimeFnPtr = ::std::option::Option<unsafe extern "C" fn() -> u64>;
pub type FlutterEngineRunTaskFnPtr = ::std::option::Option<
    unsafe extern "C" fn(engine: FlutterEngine, task: *const FlutterTask) -> FlutterEngineResult,
>;
pub type FlutterEngineUpdateLocalesFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        locales: *mut *const FlutterLocale,
        locales_count: usize,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineRunsAOTCompiledDartCodeFnPtr =
    ::std::option::Option<unsafe extern "C" fn() -> bool>;
pub type FlutterEnginePostDartObjectFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        port: FlutterEngineDartPort,
        object: *const FlutterEngineDartObject,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineNotifyLowMemoryWarningFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEnginePostCallbackOnAllNativeThreadsFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        callback: FlutterNativeThreadCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineNotifyDisplayUpdateFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        update_type: FlutterEngineDisplaysUpdateType,
        displays: *const FlutterEngineDisplay,
        display_count: usize,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineScheduleFrameFnPtr =
    ::std::option::Option<unsafe extern "C" fn(engine: FlutterEngine) -> FlutterEngineResult>;
pub type FlutterEngineSetNextFrameCallbackFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        callback: VoidCallback,
        user_data: *mut ::std::os::raw::c_void,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineAddViewFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        info: *const FlutterAddViewInfo,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineRemoveViewFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        info: *const FlutterRemoveViewInfo,
    ) -> FlutterEngineResult,
>;
pub type FlutterEngineSendViewFocusEventFnPtr = ::std::option::Option<
    unsafe extern "C" fn(
        engine: FlutterEngine,
        event: *const FlutterViewFocusEvent,
    ) -> FlutterEngineResult,
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct FlutterEngineProcTable {
    pub struct_size: usize,
    pub CreateAOTData: FlutterEngineCreateAOTDataFnPtr,
    pub CollectAOTData: FlutterEngineCollectAOTDataFnPtr,
    pub Run: FlutterEngineRunFnPtr,
    pub Shutdown: FlutterEngineShutdownFnPtr,
    pub Initialize: FlutterEngineInitializeFnPtr,
    pub Deinitialize: FlutterEngineDeinitializeFnPtr,
    pub RunInitialized: FlutterEngineRunInitializedFnPtr,
    pub SendWindowMetricsEvent: FlutterEngineSendWindowMetricsEventFnPtr,
    pub SendPointerEvent: FlutterEngineSendPointerEventFnPtr,
    pub SendKeyEvent: FlutterEngineSendKeyEventFnPtr,
    pub SendPlatformMessage: FlutterEngineSendPlatformMessageFnPtr,
    pub PlatformMessageCreateResponseHandle: FlutterEnginePlatformMessageCreateResponseHandleFnPtr,
    pub PlatformMessageReleaseResponseHandle:
        FlutterEnginePlatformMessageReleaseResponseHandleFnPtr,
    pub SendPlatformMessageResponse: FlutterEngineSendPlatformMessageResponseFnPtr,
    pub RegisterExternalTexture: FlutterEngineRegisterExternalTextureFnPtr,
    pub UnregisterExternalTexture: FlutterEngineUnregisterExternalTextureFnPtr,
    pub MarkExternalTextureFrameAvailable: FlutterEngineMarkExternalTextureFrameAvailableFnPtr,
    pub UpdateSemanticsEnabled: FlutterEngineUpdateSemanticsEnabledFnPtr,
    pub UpdateAccessibilityFeatures: FlutterEngineUpdateAccessibilityFeaturesFnPtr,
    pub DispatchSemanticsAction: FlutterEngineDispatchSemanticsActionFnPtr,
    pub OnVsync: FlutterEngineOnVsyncFnPtr,
    pub ReloadSystemFonts: FlutterEngineReloadSystemFontsFnPtr,
    pub TraceEventDurationBegin: FlutterEngineTraceEventDurationBeginFnPtr,
    pub TraceEventDurationEnd: FlutterEngineTraceEventDurationEndFnPtr,
    pub TraceEventInstant: FlutterEngineTraceEventInstantFnPtr,
    pub PostRenderThreadTask: FlutterEnginePostRenderThreadTaskFnPtr,
    pub GetCurrentTime: FlutterEngineGetCurrentTimeFnPtr,
    pub RunTask: FlutterEngineRunTaskFnPtr,
    pub UpdateLocales: FlutterEngineUpdateLocalesFnPtr,
    pub RunsAOTCompiledDartCode: FlutterEngineRunsAOTCompiledDartCodeFnPtr,
    pub PostDartObject: FlutterEnginePostDartObjectFnPtr,
    pub NotifyLowMemoryWarning: FlutterEngineNotifyLowMemoryWarningFnPtr,
    pub PostCallbackOnAllNativeThreads: FlutterEnginePostCallbackOnAllNativeThreadsFnPtr,
    pub NotifyDisplayUpdate: FlutterEngineNotifyDisplayUpdateFnPtr,
    pub ScheduleFrame: FlutterEngineScheduleFrameFnPtr,
    pub SetNextFrameCallback: FlutterEngineSetNextFrameCallbackFnPtr,
    pub AddView: FlutterEngineAddViewFnPtr,
    pub RemoveView: FlutterEngineRemoveViewFnPtr,
    pub SendViewFocusEvent: FlutterEngineSendViewFocusEventFnPtr,
    pub SendSemanticsAction: FlutterEngineSendSemanticsActionFnPtr,
}
unsafe extern "C" {
    pub fn FlutterEngineGetProcAddresses(table: *mut FlutterEngineProcTable)
    -> FlutterEngineResult;
}
