buildtools_path = "//flutter/buildtools"
is_debug = false
optimize_for_size = false
engine_version = "b29758b7708751cf7fd09556cd29a800def978ef"
content_hash = "a7e5cccc1f93392dd9f5d02dc7fd91471ffe57af"
skia_version = "0b41f940531a4fa4380f794275e7fe1b0119afa0"
dart_version = "04bcd1036cdc799ac6564988f159ee454d42c822"
full_dart_sdk = false
skia_use_libpng_decode = true
skia_use_libpng_encode = true
skia_use_rust_png_decode = false
skia_use_rust_png_encode = false
skia_use_dng_sdk = false
skia_enable_pdf = false
skia_use_x11 = false
skia_use_wuffs = true
skia_use_expat = true
skia_use_fontconfig = true
skia_use_icu = true
skia_use_xps = false
is_official_build = true
android_full_debug = false
is_clang = true
skia_gl_standard = ""
use_clang_static_analyzer = false
enable_coverage = false
enable_lto = true
host_os = "linux"
host_cpu = "x64"
target_os = "linux"
target_cpu = "x64"
dart_target_arch = "x64"
flutter_use_fontconfig = true
dart_component_kind = "static_library"
embedder_for_target = false
dart_lib_export_symbols = false
flutter_runtime_mode = "release"
dart_version_git_info = true
dart_runtime_mode = "release"
concurrent_toolchain_jobs = 16
dart_sdk_verification_hash = "04bcd1036c"
enable_desktop_embeddings = true
enable_backtrace = true
dart_disable_secure_socket = false
use_default_linux_sysroot = true
skia_use_gl = true
skia_use_vulkan = true
skia_use_vma = false
shell_enable_vulkan = true
disable_hidden_visibility = false
flutter_prebuilt_dart_sdk = true
dart_sdk_output = "built-dart-sdk"
stripped_symbols = true
angle_enable_commit_id = false
angle_build_all = false
angle_has_astc_encoder = false
angle_enable_libdrm = false
angle_use_x11 = false
angle_use_wayland = false
angle_enable_vulkan_validation_layers = false
angle_vulkan_headers_dir =
    "//flutter/third_party/vulkan-deps/vulkan-headers/src"
angle_vulkan_loader_dir = "//flutter/third_party/vulkan-deps/vulkan-loader/src"
angle_vulkan_tools_dir = "//flutter/third_party/vulkan-deps/vulkan-tools/src"
angle_lunarg_vulkantools_dir =
    "//flutter/third_party/vulkan-deps/lunarg-vulkantools/src"
